# @docs-as-code: file
#   | param: "<*>"
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: <WORKER_NAME>
  namespace: openshift-machine-api
spec:
  online: true
  bootMACAddress: <BOOT_MAC>
  rootDeviceHints:
    deviceName: <ROOT_DEVICE>
  bmc:
    address: redfish-virtualmedia+https://<BMC_IP>
    credentialsName: <WORKER_NAME>-bmc-secret
    disableCertificateVerification: true
  customDeploy:
    method: install_coreos
  userData:
    name: worker-dpu-user-data-managed
    namespace: openshift-machine-api
